services:
  keycloak:
    image: "quay.io/keycloak/keycloak:24.0.3"
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    volumes:
      - type: volume
        source: keycloak_data
        target: /opt/keycloak/data
    ports:
      - "8180:8080"
    restart: unless-stopped
    networks:
      - acmecode

networks:
  acmecode:
    driver: bridge

volumes:
  keycloak_data: